#!/bin/bash
# Test script for batch multi-file conversion

echo "=========================================="
echo "Batch Multi-File Conversion Test"
echo "=========================================="
echo ""

# Activate virtual environment
source .venv/bin/activate

echo "This script demonstrates the batch conversion feature."
echo ""
echo "Key Points:"
echo "  - ALL files are read completely (not just previews)"
echo "  - ALL files are sent to the agent in ONE request"
echo "  - Agent converts ALL files together with full context"
echo "  - Imports are generated automatically"
echo ""

echo "=========================================="
echo "Test 1: Batch Conversion with Dependencies"
echo "=========================================="
echo ""
echo "Files:"
echo "  - example_function.m (defines add_numbers function)"
echo "  - example_script.m (calls add_numbers)"
echo ""
echo "Command:"
echo "  python matlab_to_python_converter.py example_function.m example_script.m --output test_batch/"
echo ""
echo "Expected Result:"
echo "  - test_batch/example_function.py (Python function)"
echo "  - test_batch/example_script.py (with 'from example_function import add_numbers')"
echo ""

# Uncomment to run:
# python matlab_to_python_converter.py example_function.m example_script.m --output test_batch/

echo "=========================================="
echo "Test 2: Verify Batch Conversion"
echo "=========================================="
echo ""
echo "After running Test 1, check the output:"
echo ""
echo "  cat test_batch/example_function.py"
echo "  # Should contain: def add_numbers(a, b):"
echo ""
echo "  cat test_batch/example_script.py"
echo "  # Should contain: from example_function import add_numbers"
echo ""

echo "=========================================="
echo "Test 3: Run Converted Code"
echo "=========================================="
echo ""
echo "Test that the converted code works:"
echo ""
echo "  cd test_batch"
echo "  python example_script.py"
echo "  # Should print: The sum of 5 and 10 is 15"
echo ""

echo "=========================================="
echo "How Batch Conversion Works"
echo "=========================================="
echo ""
echo "1. Read ALL files completely:"
echo "   - example_function.m: 'function result = add_numbers(a, b)...'"
echo "   - example_script.m: 'x = 5; y = 10; sum = add_numbers(x, y)...'"
echo ""
echo "2. Build single prompt with ALL files:"
echo "   'Convert the following MATLAB files to Python...'"
echo "   '============================================================'"
echo "   'FILE: example_function.m'"
echo "   '============================================================'"
echo "   '[complete content of example_function.m]'"
echo "   '============================================================'"
echo "   'FILE: example_script.m'"
echo "   '============================================================'"
echo "   '[complete content of example_script.m]'"
echo ""
echo "3. Send to agent in ONE request"
echo ""
echo "4. Agent analyzes ALL files together:"
echo "   - Sees that example_script.m calls add_numbers()"
echo "   - Sees that add_numbers is defined in example_function.m"
echo "   - Decides to generate import statement"
echo ""
echo "5. Agent returns ALL converted files:"
echo "   {"
echo "     'example_function.py': 'def add_numbers(a, b): ...',"
echo "     'example_script.py': 'from example_function import add_numbers...'"
echo "   }"
echo ""
echo "6. Validate ALL files (if any fail, regenerate ALL)"
echo ""
echo "7. Write ALL files to output directory"
echo ""

echo "=========================================="
echo "Advantages of Batch Conversion"
echo "=========================================="
echo ""
echo "✅ Full Context: Agent sees complete content of all files"
echo "✅ Automatic Imports: No manual import fixing needed"
echo "✅ Consistent Style: All files converted with same context"
echo "✅ Single Operation: One API call for all files"
echo "✅ Better Results: More intelligent conversion decisions"
echo ""

echo "=========================================="
echo "To Run Tests"
echo "=========================================="
echo ""
echo "Uncomment the test commands in this script and run:"
echo "  bash test_batch_conversion.sh"
echo ""
echo "Or run manually:"
echo "  python matlab_to_python_converter.py example_function.m example_script.m"
echo ""
